version: "3.8"

services:
    postgres:
        image: postgres:latest
        restart: always
        ports:
            - 5432:5432
        volumes:
            - postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
        networks:
            - server

    adminer:
        image: adminer:latest
        networks:
            - server
        ports:
            - 8080:8080
        restart: unless-stopped
        tty: true

volumes:
    postgres:

networks:
    server:
